
source 'https://rubygems.org'

gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3', '~> 1.3.6'
gem 'pry'
gem 'nokogiri'
gem 'httparty'
gem 'tty-prompt'
gem 'artii'
gem 'colorize'
gem 'rainbow'
gem 'tty-spinner'
gem 'formatador'
