syhdmmNNmmdhysooshmMMMNmdhysssydmmNNNNNmdhyssyhmMMMMmmdhsooosyhmmNNmmddhsoosyhNMMNmdhsooosyhdmNNmmmd
//////+syyyyso+++/oNMm+yyso++//////+oyyyyso+++//mMMmosyys++///////osyyyso++++-dMNysyys++///////+syyy
--:-:++ossso+:/+++oNMm+yys/----:::++osyss+:/+++/mMMmsyyy+.---:--+++ssys+/:++o:mMNysyyo-.--::-/++osys
:-.-+/s+osso/-`-/+oNMm+hs+-`.:-..//ooosso+:../++mMMmsyy+:.`-:..//+sosss+:..:o:dMNysyo:.`-:-.-+/oosss
::.:+/sssyhs/-`.//sNMm+ys/-`-::-:+/osoyhs+-``:++mMMmsyy+:`.::-.+/+soyhyo:.`-+:mMNysyo:..:/-.++/ssshh
--.:o+ssoyys/-`:/+oNMm+hy+-..---:o+ssoyhy+-`-/++mMMmsyyo:..----+oososyy+:../o:mMNysyo:-..--./o+sosyy
---:++oossso/-.:+/oNMm+hy+:..--.-/oososso+:.-+++mMMmsyyo:.-----/++sssss+:.-/o-mMNyshs/..----:+oossss
:///+/oyyyyso+/:/:oNMm+sss+::::/+//+syyyso+///:/mMMmssss+::::/++/+syyyyo+//:/-mMNyosso/:/://+/+syyyy
yddmNNNNNmhyoooshdNMMMmmdso//oyhdmmNmmmdyo+/+shmNMMMNmdyo++sydmmNNNNNmhs+//oydMMMNmmdyo++oshmNNNNNmm
MMMMMMdsyyso+///+oosyyhhyyso+/+/yNMMhyyyso+///+ossyyhhyyso+/+/hMMMMdsyyso+////+oosyyyyyso+/+/+MMMMMM
MMMMMMysyys/:/:////++syyyso/+/+/sNMMssyss::::////+osyyys+/+/+/yMMMMhoyys/::::///++syyys+///++/MMMMMM
MMMMMMyshs+-..--../+++ssso/--/+/sNMMssys/...--.-/+++sso+/-:/+/yMMMMhshy+-`.--../+++osso/--:+o/MMMMMM
MMMMMMysyo/.`:::.:+/sosyyo/-`.//sNMMssyo:.`/::.//:yosyyo/.`.//yMMMMhoyo/-`-::.-o/osoyyo/-`./o/MMMMMM
MMMMMMysys/-`-:-./o+ssshhs/-`-//sNMMsyyo:.`-:-./o+ssshhs/.`-+/yMMMMhsys/-`.:-.:o+ssshhy+-`-/o/MMMMMM
MMMMMMyshs/-.---.:o+sooyyo/-`:++sNMMsyho/-.---./o+yosyso/..:o/yMMMMhshy/-.---.-ooooosyo/-.:+o/MMMMMM
MMMMMMysys+----://++osyyso+:-:/:sNMMssys+---:://++ssyyso/-::/:yMMMMhoyso:--::/+++osyyso+:://+/MMMMMM
MMMMMMdsyso+///+oossyhhhyso+/://yNMMhsyso////+oossyhhyyso+/://dMMMMmyyso+///+osyyhhhhhyo+///+yMMMMMM
MMMMMMMMMMNNmNMMMMMMMMMMMNNmmNMMMMMMMMMMNmmNMMMMMMMMMMMNmddmNNMMMMMMMMMNmmmmNMMMMMMMMMMNmmNMMMMMMMMM
osyhddddmdhhyo++symMMdddyso+oosyhdddmddhyso+osymMMMMmyyyso+//++osyyhhhhyso+/++oMMMNhhhyoo++++ssyhhhd
//////+syyyyo++/+/sMMoyyyo+////////osyyyso++/+:hMMMMhoyys+:////+/++syyyso/+/++:MMMNssyso/////+//+osy
----/++osyso/:/++/sNM+yyy+-..----/++osss+/:/++:hMMMMdoyyo-`.--..:+++osso/:-/+o:MMMNsyys/...--.-/++os
:-.://s+ssso/-`-+/sMMoyy+:.`::-.://sosyso/.`-+/hMMMMdoyo/-`-::.-o:osoyyo/-`./o:MMMNsyy+:..::-.//+sos
/:./+/soshhs/.`-//yMMoyyo:.`:/:./++yoshyo:.`-+/hMMMMdoys/-`.::.:o/sssyhy+-`-/o:MMMNsyy+:..:/-.+++soy
---/o+yosyyo/.`:+/yMM+yyo:-..-.-/ooyosyyo:.`/+/hMMMMhohy/-.---.-ooososyo/-.-+o:MMMNsyyo:-.----/oosos
---/++ssssso/-.:+/sMM+yys/..----/++sssss+/--/+:hMMMMdoyso:---::/++osyyss+:-:/+:MMMNssyo/----::/++osy
/:///+osyyyso+/::-sMMoosso////:///+ssyyyso+/::-hMMMMmsyso/:::/+oosyyhhyso/:::/oMMMNysso+/:::/+oooyyy
dmNMMMMMMNmdyssydNMMMMNNdhysyhmNNMMMMNNmdhyshmNMMMMMMMMMNmmNNMMMMMMMMMNNmmmNMMMMMMMMMNmdhdmNMMMMMMMM
MMMMMMMMdhhyso+++osyyhdddhhyso++oodMMmddhso++oosyhdddddhyyo++oshMNdhhyoo+++osyhhdddhhys+++oomMMMMMMM
MMMMMMMNssyss/////+///osyhyso++/+/yMMhoyys+////////+syyyys++/+++MNssyss/////+//+oyyhyso+//+:hMMMMMMM
MMMMMMMNssyy+...---./++osss+/-/++/yMMhoyyo-..----:+++ssso/:/++++MNssys+...---./++osso+/-/+o:hMMMMMMM
MMMMMMMNysyo:.`::-.//:sosyso:.`-+/yMMhoyo/-`-:-.-+:ooosso/-`./++MNsyy+:.`::-.///sosys+:.`-+:hMMMMMMM
MMMMMMMNssyo:.`::-.++/ssshhs/.`-+/yMMhoys/.`-::./o/sssyhs+-`-/++MNsyyo:.`::-.+++ssyhho:.`-+:dMMMMMMM
MMMMMMMNsyho/-..--./o+yosyyo/..:+/yMMhohs/-..--.:o+ssoyyo/-.-+++MNsyyo:-.---.+o+sosyy+:../o:dMMMMMMM
MMMMMMMNssys/----::/++ssysso/--/+:yMMhoys+-.--:-:++osssso+-.:+/+MNssys/.---::/++ssysso/--/+:dMMMMMMM
MMMMMMMMyssso/:/:/+++osyyyyso+::/:hMMhosso+:/://+++syyyyso+/:::oMNysss+/:://+++osyyyys+/::/:dMMMMMMM
MMMMMMMMMNNmmdddmNNMMMMMMNNmdddmNNMMMMNNmdhhhdmNNNMMNNNNmdhhhmmNMMMNNmdddmmNNMMMMMMNNmdddmNNMMMMMMMM
