+ooyhdmNNNmmdhyooosmMMNNNmdhssosydmNNNNNmmdhsssymMMMmmmmdhso+osydmmNNmmmdysoosyMMNmmmdhyo+osyddmNNmm
//////:/+syhyyso++:hMm-osyyyo////////+syyhyso++/sNMm//syhys+///////+osyhyyo+++:MNo/ssyys+//////:/osy
----/+::/osssoso++:hMm.oyyyo/----:+/:/osysoso++/sNMm/+syy+/-----+/-/+sssoso+++:MNo/syyo/:----++::+ss
:-`:+:o-:osso+/::+:hMm-ssso+::-`.+/+::+ssso/::+/sNMm/oyso+::-..+///-+ssso/::/o:MNo+yss+/::.`/+//-/os
::./o/o//syyo+/-:+:hMm-ssso//::.:o/++:syyo+/:://sNMm/+sso+//:.-o//+:oyyso/::/+:MNo/sso+//:..++/+:+yy
-../s+o::syso+///+/hMm-syso+::-.:o+o+:oyyo+///+/sNMm/oyyo+/--.-oo++:+yys+////o/MNo+yyso/:-..+o++:+sy
-..:+++:/osso+//+o:hMm.syyo+:-..-+o+//+sss+//+o/sNMm/+sys+/-...+o+//+osso+/+++:MN+/sys+/--../o+//+os
::/++/++osyyyso+//-hMm-+syyo+:://+//+osyyysoo//:sNMm//osys+/:/+++/+osyyysso//::MNo/osys+/://+//+osyy
syhdmmNNNNNmhyoooshNMMmmmmdyo//oyddmmNNmmdyo+/+smMMMNNNmdys++shdmNNNNNNmhs+//ohMMNNNNmhyo++oshmNNNNN
MMMMMMhoyyyys+////+oosyyhhyys++/:dMMyoyyyys+///++oosyyhhyss++/:mMMMh+syyys+/://++oosyyhhys+++/yMMMMM
MMMMMMo:oyyso+::///+//osyysss+++:hMM+/syhso/::///+/+oyyysso+++:mMMMs:oyyyo+::///+//osyyyss+/o/yMMMMM
MMMMMMo/syyo/:-.../+/./osso+o+++/hMM+/syyo/--..-++:-/osso+o++o:mMMMs:syyo/:-...+//-:+sso+++/++yMMMMM
MMMMMMo/ssoo//:-./+/o-/ssso+/-:+/hMM+/sso+//:-./+:o-/ssso/:-:+:mMMMs/osoo//:-.:o/+::oyso+/-:+/yMMMMM
MMMMMMo/ssso//:../o+o:/yyyo+/:/+/hMM+/sss+//:..+o/o:+yyyo+::/+:mMMMs/ssso/::../s+o//yhyo+//:++yMMMMM
MMMMMMo/yyso+:-..:o+o-/osso+///o/hMM+/yyso/:-../s+o-/osso+//+o:mMMMs/syso/:-..:oo+::osso+//+o+yMMMMM
MMMMMMo:osys+:--:/+/++osssso+/+/:hMM+/oyyo+:--:/+/++osssso+//+:mMMMs:oyys+/-::/++++osyyso++/+/yMMMMM
MMMMMMhosyyso+///+oosyyhhyyso/::/dMMyoyyyso+/:/+ossyyhhyyso/::/NMMMdsyhyyo+///+ssyyhhhhyso+::/dMMMMM
MMMMMMMMMMMMNmmNMMMMMMMMMMMMNNNNMMMMMMMMMNNmmNMMMMMMMMMMMNmddmNNMMMMMMMMMNmmmmNMMMMMMMMMMNmmNMMMMMMM
++osyhddmdddhys++osmMdhdddhs+++osyhddmmddhys++osNMMMdsyyhyy+/:/+oosyyhhhhyso++/yMMNyyhhhys+//+ossyhh
////////osyhyys+++/dM:+syyys+://////+oyyhyys+++/mMMMy:osyyo+::///+//osyyyss+/+/sMMm/+syyso/:///+//+s
...-/+::+sssoooo++/dM:+syyo/-...-/+::+sssooo+++/mMMMy:syys/:-.../+/-:+ssooo+++/sMMm/+yyy+/-...-+/-:+
:../+/o-/osso+/::+/dM:+sso+:::../+/+-/osso+/:/++mMMMy:ssso///-.:o/+/:osso+/-:+/yMMm/oyso+/::..+///-+
:-.++/o:+yyso+::/+/dM:+sso+//:.-++/o:+yyso/::/++mMMMy:ssso/::-./s/+//shyo+/://+yMMm/osso+/::.-o+/+:o
.../s+o-/syso+///+/dM:+yys+/-..-+o+o-+syso/://++mMMMy:syso+:-..:oo+/:osso+///o+yMMm/oyys+/-..-+oo+:+
-.-/o++:+osso+//++/dM:+sys+/--.-/o/+/+osso+//+++mMMMy:oyys+/---:+++++ssyso++/+/yMMm/+syso/---:/++/+o
///////+osyyyso//::dM/:osyso+//////+ossyyyso+/:/mMMMdosyyso+:::/oossyyhyyso/:::yMMNo+ssss+/:/:/+oosy
yydmNMMMMMMNmdyssydNMMMMNmdhysyhmNNMMMMMNmdhyshmMMMMMMMMMMNmmNNMMMMMMMMNNNmmmNMMMMMMMMMNmdhdmNMMMMMM
MMMMMMMMdyhhhys+//+osyhhddddhys++++NMmhdddhyo+++oyhddddddhyso+++mNhyhhhys+//+osyhhdddhhyo++++MMMMMMM
MMMMMMMN+/syyss+://+///+oyyhyso+++-NMy:osyys+///+////osyyyys+/+:hm+/syhso+://////+oyhyyso+++-MMMMMMM
MMMMMMMN+/syyo/-....++:-/ossooo++o-NMy:syys/:-.../+:-/osssooo++:hm++syy+/-...-++--+ossooo++o-MMMMMMM
MMMMMMMN+/sso+//:.`/+:+-/osso+:-:o-NMy:ssso/::-`:o:+:/osso+/::+:hm++sso+//:..+//+-/ssso/:-/o-MMMMMMM
MMMMMMMNo/sso+:/:..+o/o:+yyyo+::/+-NMy:ssso//:-./o/+//yhyo+/::+:hm++sso+//:..o+/+:oyys+/::/o-MMMMMMM
MMMMMMMN++yyso/--..+s+o:/ssso////o-NMy:yyso+:-../s+o//oyso+///o:hm++yyoo/--..+s++:+sss+///+o-MMMMMMM
MMMMMMMN+/syyo+:---/+++/oosso++/++-NMy:syyo/:---:++//+osss+//++:dm+/syyo/:---/++++ossso+/+++-MMMMMMM
MMMMMMMMs+oyyso/::/++++osyhyss+/::-NMh/osyso+////+++osyyysso+/:-dNo+syys+/://+++oosyyyss+/:::MMMMMMM
MMMMMMMMMMMMNNddddmNNMMMMMMNNmdddmNMMMNNNNmdhhhdmNNMMMMNNmmdhhhmMMMMMNNmddddmNNMMMMMMNNmdddmNMMMMMMM