yooooyhdmNNNmmdhysooNmmNNNNmdhssosydmNNNNNmmdhyssmMmddmmmmdhso+oshdmmNmmmdhysooyNddmmmmdhsooosydmmNm
s++/////:/oyyhysso+-m/./++syhs++////://osyyyssoo.yMs.//+shhyo+/////:/+syyyysso:+h.:/+oyhyo+/////:/+o
+:-./o/--/+osyysso+-m/-++oysso/-.:+/--:+osyyysso.yMy./++syso/-.-++:-:/ossyysso:+h-:++syso+:..++:--/+
o:`:+:o-.:/ooooooo+-m+-o++oooo:.-+/+:.-/oooooooo-yMy-+o/+oso/.`+//+.-/+oooo+os:+d-+o++oso+-`/+/+..:+
o/./+/o/.+ooooo+oo+-m+-o//+oss/.:+/++./ooooo+ooo-yMy-++/+oss+--o/++-:ooooo+o+o:+d-/+//osso-.++/+-:+o
+:./s+s:./+oooosoo+-m+-so++sso:.:s+o+./oooooooos-hMy-oo++sso/--oo++.-+ooooooos:+d-+o+ooso/-.os+o--++
+:.:oo+:-:/ooossss+-m+.oooosso:.-+o+/.-/+oooosso-hMy.++oosso/-.+o+/--:+ooossss:+d-/+oosso/-./oo/:-:+
o+/////+++ssyyyoo+/.m+.:/+syyo+//+//+/+osyyysoo+.hMy.:/+syys+/////+++osyyyso++:+d-:/+oyyso+/+//+++os
hysyhdmmNNNNmmhsoosyNmdmmmmmdyo/+oydmmmmmmmhyo+++mMNmmNNNmdhsooshdmNNNNNmmhs+++ymmmNNNmmhyo++oydNNNN
MMMMMm++ssyyhyo+////+ooyyhhhyso+/:mm/+ssyhhyo/////+osyyhhyyso+::MMm+/oosyhyo+/////+ooyyhyysso/:dMMMM
MMMMMm.:++oyyyo//:/+///+oyyhysoo/:md`/++syyso//:/+///+syyhysoo/-MMm::++oyyyo+/:/+///+osyyysos+-hMMMM
MMMMMN-/++osso+-../+/..:/oosysoo+:mm`/++osso+-`-++/..:/oosysoo/:MMm/:o+osss+:..++/-.-/oosssoso:hMMMM
MMMMMN./o+/ooso:./+/o-.:+oooo++o+:mN./+//oss+:./+/o--/+ooo++oo/-MMm//++/+sso:`/+/+:./+oooo+ooo:dMMMM
MMMMMN./o/+ooso:./o+o:-osooooooo+:mN.++++oss+--+o+o:-ooooooo+o+:NMm//o++osso:.+o+o:-+soooooooo:dMMMM
MMMMMN./ooooss+:./sos-.:+oooosss+:mN`+ooooso/-./s+o-.:+oooosss+:MMm//ooooss+:.:ooo:.:/ooooosso:dMMMM
MMMMMN.//+osss+:-/+++///ossssso+/:mN`//+ssss+:-/+++///ossssso+/:MMm/-/+oyys+/:/++++//ossyssoo+-dMMMM
MMMMMNo+osyyyyo+///+ossyyhhyso+/::mN+oosyhyso+///+ossyyhhyso+/::MMNyosyyhhyo+//+ossyyhhhhys++:/dMMMM
MMMMMMMMMMMMMMNmmNMMMMMMMMMMMNNNNNMMMMMMMMMNNmmNMMMMMMMMMMMNmddmNNMMMMMMMMMNmmmNMMMMMMMMMMNNmNNMMMMM
s+++osyhddddddhyso+odyhhddddys+++osyhdddmddhyso+sNMNo+ssyhhys+///++osyyhhhysso+:dMhosyyhhhyo+//+osyy
o+///+///+syyhysso/:s./++syhyo+///////+syyhysoo:/NMm/-++oyyyo+///+///+osyyysos+-hMs-/++syyso+///+///
+-../+:--/+osyysso/:s./++ssso/-.-/+:-:/+ssyysso:/NMm/:o+osss+:.`++/..-/oosysoso-hMs-/o+ssso/-`-++:.-
+-`/+/o..:+oooo+os/:y.+o++oos+-.///o..:+oooo+os/+NMm/:o+/+sso/.:o:+:.:+oooo+ooo-hMy-++/+oss+..+//+.-
o:./+/o--+oooooooo/:y.o+/+ooso--++/o-:ooooo+o+o/+NMN/:o/+ooso:./o/o/-+soooooooo-hMy-o+++oss+.-o++o./
/--+sos--/ooooosos//y.oo++oso/--+ooo.-+ooooooos/+NMN/:ooooss+:.:ooo:.:++oooooss-hMy-osoooso/-.ooo+.-
+:.:o+o:::+ossssso//y.+++osso/--/o+o-:/+ossosso:+NMm/-/+osss+/-:+++///+sssssoo+-hMs-//ossso/--/o+//:
o+++////++ssyyss++::y.:/+oyyyo+/+////++ssyyso++-+NMNs+ossyyso+:://oossyyyyso+/:-hMh//+osyys+///:/+oo
hyyydmMMMMMMNNmdhyyhNMMMMMNNdhyyyhmNMMMMMNNmdhyydNMMMMMMMMMMNmmNNMMMMMMMMMNNmmNNMMMMMMMMMNmdddmNMMMM
MMMMMMMmoyyhhdhyo+//+osyhhdddhysso//Nyyhddddhso+++oyhdddmddhyso+/hoyyhhdhyo///+osyhddddhyso+/oMMMMMM
MMMMMMMd./++oyhyo+///+///+syyhysoo/-m--++oyhys+///+///+oyyhysoo+.o./++shyyo+///+///+syyhysso:/MMMMMM
MMMMMMMm./++syso/-..++:.-:+osyysso/-m::++oyso+:../+/.-:+osyyssso.s./++ssso/-.-++:.-:+osyysso//MMMMMM
MMMMMMMm./o+/oss+-.+//o-.:+oooo+oo/-m::o+/osso:`:+:+:.:/oooo+ooo.y.+o/+oss+-.+//+.-/+ooo++oo//MMMMMM
MMMMMMMm.++/+oss+-.++/o::ooooooo+o+-N:/+/+ooso:.+o/o/-+ooooooooo.y.++++oss+--o+/+-:ooooooo+o//MMMMMM
MMMMMMMm.+ooooso/-.+s+o-./+oooosos+-m:/so+oso+:./s+o:./+ooooooso.y.+ooooso/--+s+o--/+oooooos//MMMMMM
MMMMMMMm.//+osss+:./+++::/+ossssoo/-N::++osss+:.:oo//::+osssssso.y.//+osso/--/+++::/osssssoo//MMMMMM
MMMMMMMN:/+osyys+/////++osyyyyso+/--N/:/+oyyso+////+++osyyysoo+:.y:/+osyys+/////++ossyyyso+/-/MMMMMM
MMMMMMMMNMMMMMNmddddmNNMMMMMNNNmmdmmMNNNNNNNmdhhhdmNNMMMNNNNmdhhdNNMMMMNNmdddmmNNMMMMMNNNmddmmMMMMMM
