mhysoooyhmmNmmmddhsosydmmNNNNmdhssoshdmNNNNNmddysyNsyhdmmmmmdhso+oshdmmNmmmdhys+syhdmmmmmdhso+osydmm
hys+///////+syyyyyo-.`////+oyhyso+//////+ssyyyys-/m`:+/:/oyhyyo///////+osyyyys/`.-////oshyys+///////
ys+:/+/--::/+yyyyyo-.`/++/+osyso/:++--::/+syyyys:/m`:++/+ooyso/:++:---:/syyyhs/..-++/+oosyo/-++:---:
ys/++:o:.---/+osyys-.`+o/:::oss+/+:+/.---:+ssyyy::m`/o+:-:+ss+/o:/+.---:+osyyy/..:o+:--+syo/+/:+----
ys+++/++-//:/+osyys-.`++/-.:oyy++o:+o-:/::+ossyy:/m`/o/:.:+syo+o//+::/::/osysy/..:o/:.-/syo/o+/o::/:
yo++s+o/.::-:+syyys-.`+o+/-:oss++s+o+-:/::+oyyyy:/m`/s+/::osso+so+o--/-:/osyyy/..:oo/:-+sso/oo+o:-/:
ys++ooo:---:/osyyyo-.`+++///oss+/oo++----/+syhyy:/m`:++///osso/oo++--.-:+ssyyy/..-++///+sso/+oo+:---
yyso+//++/++ssysso+-.`::::/osyyso+//++//+ossysso-/m`-:::/oyyyso+//++//+osyssso/.../::/osyyso+///+//+
mdhysshdmmNNNNmdhyoooyhdmmmmmmdyo/+shdmmmmmmdhso/+NhdmmNNNNmdhs+syhdmNNNNNmdhs+/oydmmNNNmmhyo++sdmNN
MMMMM/-+ooosyhhyo+////+osyyhyyys+-y-:+oooshhhyo+///++osyyhyyys+-dNo-/+++oyhhyo+/////+osyyyyyso-oMMMM
MMMMM:.++//osyyyo//+/////+syyyyy+-y.-++//oshyso//+////+osyyyyy+.dN+./+//+syyyo//+/:///+oyyyyyo-oMMMM
MMMMM:.o+///+oyo/:+/+...-:/syyyyo-y.-o+///+sso//+//...-:+syyyy+.dN+-+o///+oss+:+//-...-/syyyys-oMMMM
MMMMM:.o+/.-/sys/++:o:.:--/+osyyo-y.-o+:.-/syo/+/:o:.:--/+osyy+.dN+-++/../sys+++:+/.::-/+osyys-oMMMM
MMMMM:.s+::-/oys+oo/o/-+/:/+oysyo-y.-o+:--+syo+o+/o/:+/:/osysyo.dN+-++/:-/oys/oo/o/-/+::+sssys-oMMMM
MMMMM:.so+/:/sso++s+s:.---/+syhho-y.-so+::+sso/+s+s:.---/osyhyo.dN+-+oo/:/sss++ooo/.---/+syhhs-oMMMM
MMMMM:.++//+osys+++++//::/osyyys+-y.-++//+oyys+++++//::/oyyyys+.dNo.////+oyyso+++++/://osyyyso-oMMMM
MMMMM+:++osyyhyyo+///+ossyyyyyso/-y::++osyhhyso+///+ossyyhyyso/-dNy/+osyyhhhyo+//+ossyhhhhyys/:sMMMM
MMMMMMMMMMMMMMMMNmmNMMMMMMMMMMMMNNNMMMMMMMMMMNNmmNMMMMMMMMMMMNmdmmNNMMMMMMMMMNmmmMMMMMMMMMMMNNNmNMMM
dyso++osyhddddddhyo/+syhhhddddys+++oshhddddddhyo/mNs:+ososyhhys+///++osyhhhyyso:od++sssyhddhyo+//+os
hys+//////+osyyyyy+.`:++//oyhyyo+//////+oyyyyys/.mNo./+//+syyys+/+////++oyyyyys-+h-:/+/+oyhyso//////
so/:/+:--:::oyyyyy+-`-++//+osso/:/+:---:/oyyyyy/.mNo./+///+oss+:+//-...-/syyyys-+h-:++/++osso::++:.-
yo/+/:o-.---/ossyyo-`:o+:-:+syo/+/:o.---:/ossyy+.mNo.++/-./oys+++:+/.---/+osyyy-+h-/o+:.:+syo/o//+--
ys+o+/o:-+/:/+osyyo-`:o/:--+syo+o//o::+/:/+oyyy+.mNo.++/:./oys+oo/+/-/+::+ossyy-+h-/o/:--+syo/o+/o-/
so+oo+s:-::-/+yyyyo-`:so/::+sso+oo+s--:::/oyyyy+.mNo.+oo/-/oss++ooo/.---/+syyhy-+h-/oo/::+sso/oooo--
so/+o+o::--:+ssyyy+-`:++///+sso/+o+o-:--:+ssyyy/.mNo.////+osyso+o++//::/+syyyys-+h-:+///+oyso/++++/:
yyso+/////+oosssso/-`.-::/+syysso+/////+oosssso/.mNs-/++osyhyso+/:/+oossyyyyso/-+d:-//+osyyyso+/:/++
mdhyyydmNMMMMMNNmdhyhmNMMMMMNmdhysyhNMMMMMMNNmdhyNNMMMMMMMMMMMNmmmNMMMMMMMMNNNNNNMMMMMMMMMMNmdddmNMM
MMMMMMM/+syyyhddhyo+//+osyhdddhhys+:+osyhhddddhso+++syhdddddhhyo//+syyyhddhyo+//+osyhdddhhys+/mMMMMM
MMMMMMM.-+///oshyyo+//////+osyyyyy+...////+syhys+///////osyyyyyo.`-+///oshyso///////+osyyyys/-dMMMMM
MMMMMMM.-++/+++sso/:++:.---:+yyyhy+...++//++sss+-/+/----:+yyyyys.`-++/+++sso/:++:.---/oyyyhy+-dMMMMM
MMMMMMM.-o+:.-+syo/o/:o-.--:/oosyyo...oo/--/oys/++:+:.---/+osyys.`:o+:.-+syo/o//+-.--:/oosyy+-dMMMMM
MMMMMMM.-o/:--/syo+o+/o/:+/:/osyyyo..-o+:-./oys/oo:o/-//:/+ossys.`:o/:--+syo+o+/o::+/:/osysy+-dMMMMM
MMMMMMM.-so+:-+sso+os+o:.---/osyyyo..-oo+/-/sss+os+o/.:--/+syyys.`:so/:-osso/oo+o:-:-:/osyyy+-dMMMMM
MMMMMMM.-+///+osyo++o++/:-:/+ssyys+...++///+sys++oo+/---:+osyyys.`-+///+osyo/+o++::-:/ossyys+-dMMMMM
MMMMMMM--//++oyyyso+///+++ossyysso/...:///osyyyso////+++ossysso+..-//++syyyso+///+++osyyyss+/-dMMMMM
MMMMMMMNNNMMMMMNNmddddmNNMMMMMNNNNmdmmNNNNMNNNmdhyhdmNNMMNNNNNmdhdNNNMMMMNNmdddmmNNMMMMMNNNmmdNMMMMM