mmmhyo++sydmmmmmmdhyssyhdmmNNNNmdhyooshdmNNNNmmdhmsosyhhdmmNmmdhso+oshdmmmmmddys+syyhdmmNmmdhso+osyd
syhyso/:////+ooyyyo/--///://osyyyso/:////+oosyyo/y:./+////+syyyyo+/////++osyyy+/./+/://+osyyyo+/////
osysso/.--:-:osyhyo/--/+//+/:osysss+.--:::+syhhs/y:.++///+:+sysos+-.-:--+oshyy+:./++/+/:+syyoso:.-:-
ossss/o:.--..:+shhs/.:o+/-.`-+sssy++/.--..-+syhs+y:-oo/-.`./sssy+/+..--../oyhy+/.+o+:.`.:ossyo/+-.--
sysys+++.//.`-/syhs/-:o//-``.oysyy++o.:/-`./oyhs+y:-o//-``./sysyo++::/:`.:osyy+:.++/:``.:syshs+o:-//
ossyyoo+.:/.`-oshhs/.:oo/:.`-+ssyhooo-:/-`.+syhy+y:-oo/:.`-/osshs+o:-/-`./syhh+:.+o+:-`./osshy+o:-/:
osssyoo:.--../oyyho/.:oo+/-.-+sssys++.--..:+shhs/y:.o++/:.-+sssyy++----.-+syyy/:.+++/:-./ossyyo+:.--
syhys+/++///++ossso/.-:::::/+syyyso++/////+ossso/y:.:::://+oyyyyo+/+////+oosss/:.:::::/+oyyyyo+/+///
NNmdyooshdmNNNNNmdhs++shddmmmmmmdyo++shdmmmmmmdhsyooyhdmmNNNNmdhys+oydmNNNNmmdhs++oydmNNNNNmhyosyhdm
MMMMy-://++osyhhhyo+:://oosyyyyyo++.//+++osyhhyyo+://+ossyyyyso+Nd.:////+osyyyys+:://+oossyyyoodMMMM
MMMMs.//+//++osyyyso/::///+osyhyo//`//+//++oyyysso:::///+osyhyo/Nd`:+////++syyyso/::////osyhyo+hMMMM
MMMMs./o+//:.:ossss++...-.-+syhyo//`+o+//:./ossss++..-..-+syhyo/Nd.:o+//-.-+sssy++-.-..-/oyhhs+hMMMM
MMMMs.+++:```-sysys/o/.::..-/syho//`o+/-``.:sysyo/o:.:-..-+syho/Nd`/o+:.``:oysys++/.::..-/syhs+hMMMM
MMMMs.+o/:-``-oysyy+o+.+/-`-osyho//`o+/:-``:sysys+o/-+/.`:osyho/Nd`/o/::``-ossyy+o/-/+.`-+syhs+hMMMM
MMMMs.+oo+:..:ossyyoo/.--..:oyhho//`ooo/-`./ossyyoo:.:-..:oyhho/Nd`/oo+:..:ossyyso/.--..:oyhhs+hMMMM
MMMMy./+///::+syyyso+/:::::+oyyyo//`+////::+syyyso+/::::/+syyy+/Nd`:+////:+syyyyo+//:/:/+osyss+hMMMM
MMMMy--//++osyhhyyo+///+ossyyyyso++.://+ossyhhyso+///+ossyyyys++Nd-:/+ossyhhhhyo+//+osyyyhhyysodMMMM
MMMMMNMMMMMMMMMMMNNmmNMMMMMMMMMMMMNNMMMMMMMMMMMNNmmmNNMMMMMMMMMNNmmmNMMMMMMMMMNNNNNMMMMMMMMMMMNNNNNM
mddhso/+oshhdddddhy+/osyyhhddmddys+/+oyhhdddddhyyNm.:++++ssyhhhys+/:/+ossyyyhysoyo:/+oosyhhhhhyo+//+
yyhys+///++++osyhyo-`+////+osyyhyo+///+++oosyyy++Nm`-+////++syhyso/::/+//osyhys+y+-/+///++syyyso+::/
ssssso:..---/osyhyo-.++////-+syssoo:.----/osyhy++Nm`:o+//:--+ssoyo+-....-+syhys+s+-/o///:-/ossss+:..
sysys/o-.--..:+shho-.oo/-.`.:sssyo/o..--..:oyhy++Nm`:o+:.``-oysyy/+/.-:..-/syhs+s+-+++.``./sssyo++-.
sysys+o/-//.`-+syho.`o+/:.`.:yysyo+o:-+/..-oyyyo+Nm`:o/::``-+ysyy+++-/+-`-+syhs+s+-o+/:.`./sssyo+o-:
ossyyoo/./:..:oyhho..oo+/-`./ossyyoo:-/:..:syhyo+Nm`/so+/`.-+ssyyso/.-:..-+yhhs/s+-oo+/-`-/osshsoo--
ossyyoo----.-/oyyyo-.+++/:--/sysyy+o-----:+syyy++Nm`:++///:/oyyyyo+/:::::+osyys/s+-//+/:::+syyyso/::
syyys+++/://++osss+-`::-::/+osyyys+++/://+oosso++Nm`-://+ossyhyyo+/:/+oossyyyso+s+.-://++osyyyso////
MNNdhysydmNMMMMMNmmhyhdmNMMMMMNmdhysydNMMMMMMNmmdNNNNMMMMMMMMMMMmmmNMMMMMMMMMMNNNmmNMMMMMMMMMNNmddmN
MMMMMMs:+oossyhdddhyo+//+oyyhhhhhyso/+osyyhdddddhso+/+syhhddddhy/:+oosyyhdddhyo///+oyyhhhhhyssMMMMMM
MMMMMMo`/++//++syyhys+/:/++++osyyy+/.:++///+osyhyso///++++osyyyo-./+///++syyhso+///+/++osyyy++MMMMMM
MMMMMMo`+++///-/ossoso/`.--.:osyhy+/.:++///-:ossoso/..----osyhho-.+++///-/ossss+:..--./osyhy++NMMMMM
MMMMMMo`oo/-.`.:sssyo/o:.--..:+shh+/./o+:.``-ossys/+/.--..-+syho-.o+/-``.:sssyo/+-.:-..:oyhh++NMMMMM
MMMMMMo`o+/:.``:sysys+o/-+/.`:osyho/./+/:.``-oysyy/o/-//.`-+syhs..o+/:.`./syshs+o::+/`.:osyh++MMMMMM
MMMMMMo.oo+/-`./ossyy+o:.:-`.:syhho/./oo/:`.:+ssyhoo/.::.`-oyhho-.oo+/-`-/ossyy+o:-:-`.:syhh++MMMMMM
MMMMMMo`++//::-+sysyyo+:----:+oyyy+/./+++::-/ossyys+/-----/oyyyo-.+++/:::+syyyso+:----:+syyy++MMMMMM
MMMMMMo`::///+osyyyyo+///+++oosyss+/.-::///+oyyyys+////+++oossso-`:://++osyyyso////+++ossyss++NMMMMM
MMMMMMNmmNNNMMMMMNNmddddmNMMMMMMNNNmddmmNNNMMNNNmdhhhdmNNMMNNNNmdmmNNNMMMMMNNmdddmmNNMMMMMNNNmMMMMMM