
 mNmmmhyooosydmmmmmdmysssyhdmmNNNNmdhsooshdmNNNNmmMyooosyhdmmNNmmdhso+oshdmmmmddhooossydmmNmmmdhso+os
 ++syyys+//+++//osooy//+////++++syyys+///++//+ssoyN+:++///++++oyhyyo///+++/+oso+s:+////++++oyyhyo+//+
 :/syyhs:..--:/+oysoy:/+///+:-:/oyyhs:-----/+oysoyN+:++/++:.:/osyhy/-.---:+osyoos:++/+//--:+syhy+-.--
 -+oshsy/..--..:oyyoy:+o/--.``./+shyyo..--..:+syoyN+/o+:..``./+ohyss-.--..-/syo+s:o+:-.``.:+oyhss:..-
 :+oyhyyo.:+:.`-+syoy:o+/:.```-+oshyys--/:.`.+syoyN+/+/:.```./+shyys:-//.`./oyo+s:o/:-```.:+ohhyy/./+
 -/oydyyo.:/:``/oyyoy:oo/:-.`../+yhhys--+:.`:+yyoyN+/o+::.`..:+shhys:-//.`-+sho+s:o+//.`..-/ohdyy/./+
 -/oyhhy/..--.-/ossos:ooo+:-..-/oshhyo..--..:osyoyN+/oo+::.`-:+shhys-.--..:+syo+s:oo+/-...:+oyhys:.--
 +oyyyyso+//////+oo+s://:://///osyhyso+/:////+oo+sN+:/:::///+osyyyso+/:////+ooo+s:/:::////+syhyyo+/:/
 NNNNdhsooshdmNNNNmmdo//+shddmmmmmmhso++shdmmmmmmmNso+oyhdmNNNNNmmho++oydmNNNmmmdso++oydmNNNNmmdhysyh
 MMMMh//////+ossyhhhyo+///+oosyyssdy:+////oossyhhyyo////ooosyyssmMd://///+oossyyyyo+/:/+o+osssohMMMMM
 MMMMh:/+::/+/++oyyyyo/::///++sys+ds:++://+/++oyyyyo/::///++sys+mMd://::/+//++syyys/::///++ssy+hMMMMM
 MMMMh/oo///-..-/osyys-.....:+sysods:o+//:-`.-/oshys-....-/+sys+mMd:++///-`.-/oshys:..-..:+oyy+hMMMMM
 MMMMh/o+/.````:+oyhyy+`-:-.`-oyyods:o+:.````/+oyysy/.-:-``:oys+mMd:++/-````:+oyhyy+.-:-``-+sy+hMMMMM
 MMMMy/o/::.```:+oyhyyo./+:``/oyyods:s/::.```:+ohhyy+./+:``/oys+mMd:o+::.```-/oydyy+-/+/``:+yy+hMMMMM
 MMMMy/oo+/-``.-/oydhy+.-:-`./syyods:so+:.``.-/oydyy/.-:.`.+sys+mMd:oo+/-.`.-/osdhy+.-:-../syy+yMMMMM
 MMMMy:+////:-:/+syhys/:-::::/oss+ds:+////:-:/oyyhys/:-:::/+oso+mMd:+/////::/+syhys+:-::://+ss+yMMMMM
 MMMMh/:::/++ossyhhyso+///+ossyyssdy::::/++osyyhhyso+///+ossyyssmMm::://+osyyhhhhyo+//+osyyyhyydMMMMM
 MMMMNNNNMMMMMMMMMMMMNmmNMMMMMMMMMMNNNNMMMMMMMMMMMMmddmNNMMMMMMMMMNNmmmNMMMMMMMMMMNmNNMMMMMMMMMMMNNNN
 ddmddys+++oyyhddddhs+ooosyyhdddmddys+++oyhhddddhNMm//++/+ossyyhhhyo+///+sssyyyshNs/++++osyyhhdhhyo+/
 +oyyyyo+//+++++sss+/:++//+++++oyyyyo+//+++++ssoomMm:///:/+//+oyyyys+/////++oss+yNs://///++++oyhyso/:
 :+syyyo-..--:/+sys+//++//+:.-:+syyy+...--:/+sysomMm:++///:..-/osyys:....-:+oyy+yNo/o+///-..:+syyy+..
 :+oyysy:.--...:oys+//o+:..``./+oyysy-.--.`./sysomMm:++/-````-+oshyy+..:-.`-+sy+yNo/o+-.```./+ohyys-.
 /+oyhyy+./+-``:oys+//o:/-````/oohhyy/.//-``/oysomMm:++::.```-+oydyyo-:+/``-+sy+yNo/+/:-```./+ohhyy:.
 -/oydyy+.:/-`./ohs+//o+/:.`..:/shhyy:.//.`./sysomMm:oo+/-...-/osdhyo.-:-`.:oyy+yNo/o+/:.`..:+shhyy:.
 :+syhyy:-.----/sss+:/o++::-.-:+shhyy:----.:+oysomMm:++////--:+syhys+:--:-:/+ss+yNo/+///:--:/oyhhyo:-
 +osyyyso+///:/+oo++::/::::://+oyyyyso+//://+oo+omMm---::/+oosyyhyso+/:/+oossysshNo-:--:/++osyyyyso+/
 MMMNmdhssydNMMMMMNNdhyyhdmNMMMMMNmdhysydNMMMMMMNMMMNNNNMMMMMMMMMNNNmmNMMMMMMMMMNNmdmmNMMMMMMMMMNNmdd
 MMMMMMy/++++osyhhdddhyo+//+syyhhhhyd++++osyhddddddhso++osyhhdddho/++++osyhhdddhyo+//+syyhhhhyNMMMMMM
 MMMMMMy:++::/+/++oyhyyo///+++++sso+y://///++++osyhys+//+++++oss+/:+/::++/++syhyyo///+++++sso+NMMMMMM
 MMMMMMy:o+///:.-:+oshyo-...--/osys+y-++////..:/osyyo-...--/+sys+/:o+///:.-:+sshy+....--/osyo+NMMMMMM
 MMMMMMs:o+:.````:+oyysy/.--.``:oys+y:o+/-.```-+oyhss+..--.`:oyy+/:o+:.```./+ohyss:.--.`./sys+NMMMMMM
 MMMMMMs:o/::.``.:+ohhyy/./+-``/oys+y:o/::.```:+oyhyy+.:+:``:+sy+//o/:-```./+ohhys/-/+-`./oys+NMMMMMM
 MMMMMMs:so//.`..-/oydyy/.::.`.+shs+y:oo//-`..-/oydyy+.:/-``/oyy+//so//.`..:/ohdyy:.::.`.+shs+NMMMMMM
 MMMMMMs:o++//-.-:+syhys/-----:+oss+y:+++/:-.-:+oyhhs+-----:/oss+/:+++//-.-/oshhys:-----:+oso+NMMMMMM
 MMMMMMs-::::/+++osyhyso+/:/+++osssoy-:::::/++osyyyyso+:///++ooo+/-::::/++oosyhyso+/:/+++ossooNMMMMMM
 MMMMMMmmmmmNNNMMMMMNNmmdddmNMMMMMNNNhhhdmmNNMMMNNNmdhhhdNNNMMNNNmmmmmNNNMMMMMNNmddddNNMMMMMNNMMMMMMM