
 mmNNmmdhyooosydmmmNMNhyossyhdmNNNNNmdhsooyhmmNNNMMNhsooosyhdmmNNmmdhso+oyhdmmmNNdsooosyhdmmNNmmdhso+
///osyyys++/++//+/oNdoo+//+++///osyyyso+/++//+/+mMN+o+//+++///+syyyso+/+++//+/dNso+:/++++//+oyyyso+/
:-:+shyo+:-.-/++o+omdoo//+/-::::+shhs+/---:++o++mMNoo+///--:-:/oyhso/-.--++oo/dNso+/+/-.:::/+yhyo/:-
---/yyhs/:-...-/o+oNdos/-.``.---:syhy+:-...-/oo+mMNos+-.```.---syyh+/--...:+o/dNss+-.```.---ohyho/:-
::-+yyhy+/+:.`./o+oNdso/-````:::/yyhh+//:.`.:+o+mMNoo/-````-:-:yyhho/+/-`.-+o/dNso+:````.::-shhhs/+/
..-+hhdy//+:.`:/s+oNdss/:.`...--/yhhh+/+/-`-/oo+mMNos+:-`.....:yhhho/++-`./os/dNss+:-`.....-shhhs/++
--:+yhhs+:-..-:+o+omhsso/-..----/yhhy+/-...:+o++mMmoso+-...---/shhyo/:...-/+o/dNsso+:...---:ohhho/:.
//+syyyys+:://////sNho+////:://+oyyyys+::://///+mMN++/:/:////+osyyyyo//://////dNo+//://////+syyyyo/:
NNNNNmdysooshdmNNNNMmy+//+shdmmmmmmdho+++shdmmmmMMNhs++oydmmNNNNNmdyo/+oydmNNNMMdyo+++sydmNNNNmmdhys
MMMMMyo+///++oossyhhyyo+//+++osshNMso+///+ooosyyhhyso+//++oossdMMNho+///+++oosyyhyyo+//++++oosMMMMMM
MMMMMso+/:/+////+oyhyso+/::+++o+sNMoo+::+/:+//+syhyso//::+++o/yNMNho+/:/+:///+oyhyso+:::/+oo++MMMMMM
MMMMMsso//:...---+shho/:...:/+o+sNMos+/::...--:+yhyo/-...:++o+yNMNhoo/:-.`..--/yhho/:-..-/+o++MMMMMM
MMMMMss+:````.::-+yyhs/::-.`./o+sNMos+-````.::-oyyhs/::-.`./o+yNMNhoo:````.::-+hyhy//:-.`.:o++MMMMMM
MMMMMss+:-```.:--ohhhy/++/.`-/o+sNMos/:-```.:--shhhs+++:.`-/o+yNMNhs+/:``..---+hhhy+++/.`-/o++MMMMMM
MMMMMsys/:......-+hhds/::-.`:+s+sNMoyo/-`..-..-ohhhs/::-..:os+yNMNhss+:``..---/hhhs+::-..:+o++NMMMMM
MMMMMss+//:--:::+syhhso:---://+/sNMos+//:--:::+syhhs+:---///+/yNMNho+///:::::/syhhyo/---:///++MMMMMM
MMMMMs+/:::/+ossyyhhyso+///+oosshNMo+/:::/+ossyhhhyso+///+oossdMMNh+/::/+ossyyhhhhyo+//+osssyhMMMMMM
MMMMMMNNNNMMMMMMMMMMMNNmmNMMMMMMMMMMNNNNMMMMMMMMMMMNmdhmNNMMMMMMMMMNmmmmNMMMMMMMMMMNmmNMMMMMMMMMMMMN
hddmmddys+++syhhhdmNys+++osyhhddmmdhys++osyhhddNMMMdo+///+oossyyhhhys+//+oosssyMMmyo+//+ossyyhhdhyyo
//+syhyyo++//+++++smoo+//++++//+syyyso+///++++/hMMMho+/:/+/+//+oyhyyo+////++o++NMmso/:/+//+//osyhyso
--:+yhyo/-.../++o+smoo+///-.---/oyhso/-..-/+oo/hMMMhoo//:-...--/shhs+:-..-/+o++MMmso+//:..---:oyhs+/
:--+yydo/:-...-/o+smos+-.```.:--oyyho/:-...-+o+hMMMhoo:.```.-:-/hyhy+::-...:o++MMmso+.````-:--syhho/
::-ohhhs/++:.`-/o+smss/:.```.::-shhhs/++:.`-/o+hMMMhoo/-```.-:-+hhhy+++/.`-/o++MMmso/:````-:-:yhhho/
..-ohhds///-.`:+s+smoy+:-`.....:shhho///-.`/+o+hMMMhss+:``....-/hhhy+:/-..-+s++MMmss+:-`..-..:shhho/
--/ohhhs+:-..-/+++smoso+:...---/shhho/--..-//+/yMMMho++/:--:::/oyhhyo/---:///+/NMmso+/::--:::+shhyo+
//+syyyys+///::///ymo+/:/:/:://osyyyyo////::///hMMMh+/:::/++ossyhhyyo+://++ooosMMmo//:-://+oosyyyyso
MMMMMNNdhssydNMMMMMMmhyyyhdmNMMMMMNmdhysydNMMMMMMMMMNNmNNMMMMMMMMMNNmmmNMMMMMMMMMMmdddmNMMMMMMMMMMNm
MMMMMMMyo+//+osyyhhdddhyo+/+osyyhhmMdso+++osyhdddddhyso++osyhhhdNso+/++osyyhhddhhyo+/+osyyhhmMMMMMMM
MMMMMMMoo+::++/+//+syhyso+///++++/yNyo+::++/+//+oyhyys++/+++++/+Noo//:++/+//+syhyso+///++++/hMMMMMMM
MMMMMMMoo+///-.---:+yhy+/-.../++o/yNyoo///:.---:+shyo/:..-:++o/oNos+//:..---:+yhy+/-..-/+oo/hMMMMMMM
MMMMMMMos+-````.:--oyyho/:-...-/o+yNyso:.```.---/yyhs/:-...-/s+oNos+-``.`.:--syyho/:-...-+o/hMMMMMMM
MMMMMMMos/:.```.:--shhhs/++:.`-/o/yNyo+/.```.::-+hyhy+++:.`-/o++Nos/:.```.:-:shhhs/++:`.-/o/hMMMMMMM
MMMMMMMoyo/-`.....-ohhhs///-`.:os/yNyso/:......-+hhhy///:..-+s++Nos+/-`.....-shhho///.`./os/hMMMMMMM
MMMMMMMoso/:-..:-:/syhhs+:---://+/yNyoo+:-..---:oyhhs+:-..-:++/+Nos+/:-.-:::/shhyo/:---://+/yMMMMMMM
MMMMMMM++/:::/++++oyyyyso//:/+++++hNy+/:::///++osyyyys+//:///++oN++/:::/+++ooyhyyso//:/+++++hMMMMMMM
MMMMMMMNmddmmNNNMMMMMNNmmdddmNMMMMMMNdhhhdmNNNMMMNNNmdhhhdmNNNNMMNmddmmNNMMMMMMNNmdddmmNMMMMMMMMMMMM