
 hdmmNNmmdhysoosydmNMMNdhsossydmmNNNNNmdhyssyhmmNMMMNdhsooosyhdmmNmmmdysoooyhdmMMNdhsooosyhdmmNNmmdhs
////+oyyyyso+++/+:sMMhys+++++////+osyyyso+++/+:oNMMmsso++/++////osyyyyo+++++/-NMmsyo/o/++////+syyyys
:::-/sysso+:--++o:sMMhyso+-.:::::/syssso/-.++o/oNMMmsyo+:.-:::-:oyysso/-.:+o+-NMmyyo+/.-::::-+yysso+
::`-+ohsso+:.`.:o/sMMhys:.```::..+oyyso+/...:+/oNMMmys/.```-:.`/oshsso/-``-++:NMmyy+-```-:-`-sshsso+
::.:oshhsys+-``:+/sMMhys:```./:--+oyhsss+-``-+/oNMMmss/.``.:/-.+oyhssso:``-/+:NMmyy+.```-::./oshysys
--.:syhysss+.`./o/sMMhys/.`..--.-oshhssso-``:+/oNMMmyy+.`..--..+yyhssss:``-+o:NMmyyo-`..---./yyhysss
---:+shyso+:..-++:sMMyhy+.`.-----+yyyso+:-../o/oNMMmyyo-.`-----/syysso/-..:++-NMmyys:...----:syyyso/
///+osyhyso+:////:yMMyss+/:::/://+oyhhyo+::///:oNMMdss+/:::////+oyyhyso/:///::NMmss++:::////+osyhyso
dmNNNNNmdysooshdmmNMMmhy+//+shdmmmNNmdyo+/oshdmNMMMNdys++oydmmNNNNNmdyo//oydmNMMMmdyo+++shmNNNNNmmdh
MMMMMMyys+/++++oosyyhhyyo+++++oodMMNsyo+/++++oosyyhhyso+++++oomMMMNhss+++++/++osyyyyso+++++++yMMMMMM
MMMMMNsyo++:://///+syyyso/:/++o:yMMNsyo++-://///+syyyso/:/+++:dMMMNyss++:-/////+syyyyo+::/+o/sMMMMMM
MMMMMMsyo/-``.--..+sysso/:..:+o/yMMNsyo/-`..--.-+sysso/-../+o:dMMMNhys/-``.--..+sysso+:..:+o/sMMMMMM
MMMMMMyyo.```-::.:oohysso:.``:+/yMMNsy+.```:::.:oohysso:``.:+:dMMMNhyo-```-/:.-oohysso/.``:+/sMMMMMM
MMMMMNyyo:```.:-.:sshysys+.`./+/yMMNsyo-```-:-./sshysys/.`./+:dMMMNhyo:```.:-.-sshysyso-`.:+/sMMMMMM
MMMMMMyhs:``.---.-syhysso:.`.+o/yMMNsho-`..--..:syhssso:.`-+o:dMMMNhys/`..---..syhysoo:.`./o/sMMMMMM
MMMMMNsyo/:.-::://osyyys+:-.://:sMMNsso/-.-:::/+oshyyo+:.-/+/-hMMMNyss/:--::://osyhys+:--://:sMMMMMM
MMMMMMyso////+oossyhhhyso+///+oodMMNss+////+oossyhhhyso+///+oomMMMNhso/://+ossyhhdhhso+///ossdMMMMMM
MMMMMMMMNNmNMMMMMMMMMMMMNmmNMMMMMMMMMMNNmNMMMMMMMMMMMNmdhmNNMMMMMMMMMNmmmmNMMMMMMMMMMNmmNMMMMMMMMMMM
yhhdmmmdhyso+ooyhhNMNhys++oosyhhdmmmdhyso+ooyhdNMMMNhys+/++++ossyhhhhys+++++oohMMMmyyo+++ooosyhhddhh
////+syyyys+//+++/yMmsyo++/++////osyyyyo+/++++/dMMMNhss++/:+////+syyyys+::/++/oMMMdyy+/+:/+///+osyyy
----+yysso/-.-+++/hMmsyo+:..----:oyysso/-.:+++/dMMMNhys+:``.--../sysso+:..:+o/oMMMdyyo/-`.---.-oysss
:-`:oshsso+:.`.:+/yMmyy/.```-:-`:oshsso/-.`-/+/dMMMNhyo-```.::..ooyysso/.``-+/oMMMdyy/.```::-`/oshss
/:.:oshysys/.``/+/yMmys+.```:/:./oshysys/.`./+/dMMMNhyo:```.::.-sshhsyso-`.:+/oMMMdys+.```-:-.+syhys
--.:syhysss/.`-/o/yMmyy+-`..--../syhssso:``-+o/dMMMNhys/`..---..oyhysso/.`./o/oMMMdhy+-`.---../syhss
---:oshyso/:..:++:yMmyyo:.`.----/oyhyso/-..:+//dMMMNhys/:..::://osyyys+/--://:oMMMdyyo:..-::::/syyys
::/+osyyyso+///:::hMmss+///:/://+osyyyso+///::/dMMMNhso/:::/+oossyhhyso+:://++hMMMdso+/:::/++oosyyyy
NMMMMMMNmdhssydNMMMMMNdhyyyhdNNMMMMMNmdhysymNMMMMMMMMMNNmNNMMMMMMMMMNNmmmNMMMMMMMMMNmdhdmNMMMMMMMMMM
MMMMMMMNyys+++oosyyhddddhys+++osyyNMMdhso++ossyhddmddhysoo+osyhmMNyyo+++oosyyhdddhhyo+++osyyNMMMMMMM
MMMMMMMNsyo++:++////+syyyys+//+++-dMNyyo++//++///+syyyyso//+++:yMmsso/+:++////osyyyyo///+++-NMMMMMMM
MMMMMMMNsys+-`.-----+yysso/-.-/+o-dMNyys+/..-----/yysso+:.-/+o:yMmsyo/-`.---.-oyssso/-.-+o+-NMMMMMMM
MMMMMMMNsy+.```-:-`:oshsso+:``.:o:dMNyyo-```.:-.-oohyso+:.`.:o:yMmsy/.```-:-`/oshsso+-``./+-NMMMMMMM
MMMMMMMNsy+-```-:-./sshysys/.`./+:dMNyyo-```.::.:oohysys+-`.:+:yMmss+.```-:-.+sshysys/.`-/+-NMMMMMMM
MMMMMMMNsyo-`..--../syhysso:``-+o:dMNyho:`..---.-syhysss/.`./o:yMmyyo-`..--../yyhssso:``-+o-NMMMMMMM
MMMMMMMNsyo/..--:::/oyyyso+:..:++-dMNyys/-..-:--:oyyyso+:..-/+:yMmsyo:..-::::/oyyyso/-..:++-mMMMMMMM
MMMMMMMNso+/:::/+++osyhhyso/://///mMNyso//::///++osyyyso+:////:yMmso+/:::/+++osyhyyso/://///NMMMMMMM
MMMMMMMMNNmddmmNNMMMMMMNNmmddmNNMMMMMNmdhyhdmNNNMMMNNNmdhhhmNNNMMMNNmddmmNNMMMMMMNNmdddmNNMMMMMMMMMM